version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:8000
    depends_on:
      - db
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres