version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init/init.sql:/docker-entrypoint-initdb.d/init.sql